# docker-compose.yml
version: '3.9'
services:
  applemusic-bot:
    build: .
    container_name: applemusic_alac_bot
    restart: unless-stopped
    environment:
      - API_ID=11230592
      - API_HASH=594fcd9717990fb853c3cae82d65afdc
      - BOT_TOKEN=8205775273:AAHhS2A5ULbkEtpZ-2hyFazbRGdFLou8iXI
    volumes:
      - ./downloads:/app/downloads
      - ./assets:/app/assets
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
