# docker-compose.yml
version: '3.9'
services:
  applemusic-bot:
    build: .
    container_name: applemusic_alac_bot
    restart: unless-stopped
    environment:
      - API_ID=your_api_id_here
      - API_HASH=your_api_hash_here
      - BOT_TOKEN=your_bot_token_here
    volumes:
      - ./downloads:/app/downloads
      - ./assets:/app/assets
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
